title: СК Гран Мошенники
email: andrii.granuk+fraud@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Осторожно мошенники: СК Гран, Гранюк Андрей 24.12.1983
  ФОП Гранюк Андрій Валентинович, тел: (097)536-73-55
  Хмельницька обл., м. Славута, вул Лісна буд. 11 кв. 21  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ck-gran.site"

permalink: ':title/'
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Андрей Гранюк
author-img: avatar.jpg # add your photo
about-author: >- 
  ОСТОРОЖНО МОШЕННИКИ <br>
  СК Гран - возьмем деньги, вынесем вам "завтраками" мозг и ничего не сделаем. <br><br> 
  ФОП Гранюк Андрій Валентинович, <br> 
  тел: (097)536-73-55 <br>
  Код: 3067320396 <br>
  Хмельницька обл., м.Славута, вул Лісна буд. 11 кв. 21 
social-twitter: # add your Twitter handle
social-facebook: andrei.granuk 
social-facebook-group: groups/543106036358181/ # add your Facebook handle
social-linkedin: # add your Linkedin handle
social-email: andrii.granuk+fraud@gmail.com # add your Email address

# Disqus
discus-identifier: # mr-brown # add your discus identifier

# Tracker
analytics: UA-177197913-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
